config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :users do
    member do
      get 'participations'
      get 'events'
    end
  end
  resources :newsposts
  resources :sessions, only: [:new,:create,:destroy]
  resources :part_in_events do
    member do
      get 'pick'
      get 'unpick'
    end
  end
  resources :events
  resources :participates do
    member do
      get 'qualify'
      get 'disqualify'
    end
  end
  resources :leagues do
    member do
      get 'participants'
      get 'manage'
      get 'events'
      get 'closeevent'
      get 'leaderboards'
	  get 'delete'
    end
  end
  get 'static_pages/home'
  get 'static_pages/contact'
  post  '/leagues/:id', to: 'leagues#show'
  match '/searchleague', to: 'leagues#search', via: 'get'
  match '/newleague' ,  to: 'leagues#new' ,         via: 'get'
  match '/signin' ,  to: 'sessions#new' ,         via: 'get'
  match '/signout' , to: 'sessions#destroy' ,     via: 'delete'
  match '/home' , to: 'static_pages#home' , via: 'get'
  match '/help' , to: 'static_pages#help' , via: 'get'
  match '/signup' , to: 'users#new' , via: 'get'

end

app/models/league.rb
class League < ActiveRecord::Base
  has_many :participates, foreign_key:  "league_id",dependent:  :destroy
  has_many :users, through: :participates, source: :user

  has_many :wheres, foreign_key: "league_id", dependent: :destroy
  has_many :locations, through: :wheres, source: :location

  has_many :hows, foreign_key: "league_id", dependent: :destroy
  has_many :disciplines, through: :hows, source: :discipline

  has_many :admins, foreign_key: "league_id", dependent: :destroy

  has_many :newsposts, foreign_key: "league_id", dependent: :destroy

  has_many :events, foreign_key: "league_id", dependent: :destroy

  def setDisc!(some_discipline)
    hows.create!(discipline_id: some_discipline.id)
  end
  def isAdmin?(some_user)
    admins.find_by(user_id: some_user.id)
  end
  def setAdmin!(some_user)
    admins.create!(user_id: some_user.id)
  end
  def kickAdmin!(some_user)
    admins.find_by(user_id: some_user.id).destroy
  end
  def participate(some_user)
    participates.create!(user_id: some_user.id)
  end
  def isParticipating?(some_user)
    participates.find_by(user_id: some_user.id)
  end
  def unparticipate!(some_user)
    participates.find_by(user_id: some_user.id).destroy
  end
  def hasDisc?(some_discipline)
    hows.find_by(discipline_id: some_discipline.id)
  end

  def unSetDisc!(some_discipline)
    hows.find_by(discipline_id: some_discipline.id).destroy
  end

  def place!(some_location)
    wheres.create!(location_id: some_location.id)
  end
  def placed?(some_location)
    wheres.find_by(location_id: some_location.id)
  end
  def displace!(some_location)
    wheres.find_by(location_id: some_location.id).destroy
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  def new
    @league= League.new
  end

  def create
    @league= League.new(league_params)
    @league.save!
    li= Location.find_by(id: league_params[:loc])
    if li.name == " Other"
      l=Location.new(:name => league_params[:slocation])
      l.save!
      @league.place!(l)
    else
    l = Location.where("id = ? ", league_params[:loc]).first
      @league.place!(l)

    end

    di= Discipline.find_by(id: league_params[:discipline_id])
    if di.name == " Other"
      d=Discipline.new(:name => league_params[:sdiscipline])
      d.save!
      @league.setDisc!(d)
    else
    d= Discipline.where("id = ? ", league_params[:discipline_id]).first
    @league.setDisc!(d)
    end
    @league.setAdmin!(current_user)
    @league.save!
    redirect_to @league
  end
  def show
    @league =League.find(params[:id])
    @participate= Participate.new()
  end
  def edit
    @league =League.find(params[:id])
  end
  def manage
    @league =League.find(params[:id])
    @newspost= @league.newsposts.new()
    @newspost.league_id= @league.id
    @event= @league.events.new()
    #@newsposts= Newspost.new()
  end
  def search
    li= Location.find_by(id: params[:location_id])
    di= Discipline.find_by(id: params[:discipline_id])
	if(li.nil?)
      li= Location.find_by(name: " Other")
    end
    if(di.nil?)
      di= Discipline.find_by(name: " Other")
    end
    if li.name == " Other" && di.name == " Other"
      @leagues= League.all.paginate(page: params[:page])
    elsif li.name == " Other"
      @leagues = League.joins('JOIN wheres ON wheres.league_id = leagues.id')
      .joins('JOIN locations ON wheres.location_id = locations.id')
      .joins('JOIN hows ON hows.league_id = leagues.id')
      .joins('JOIN disciplines ON hows.discipline_id = disciplines.id')
      .where("hows.discipline_id = ? ",params[:discipline_id]).paginate(page: params[:page])
    elsif di.name == " Other"
      @leagues = League.joins('JOIN wheres ON wheres.league_id = leagues.id')
      .joins('JOIN locations ON wheres.location_id = locations.id')
      .joins('JOIN hows ON hows.league_id = leagues.id')
      .joins('JOIN disciplines ON hows.discipline_id = disciplines.id')
      .where("wheres.location_id = ? ", params[:location_id]).paginate(page: params[:page])
    else

    @leagues = League.joins('JOIN wheres ON wheres.league_id = leagues.id')
                      .joins('JOIN locations ON wheres.location_id = locations.id')
                      .joins('JOIN hows ON hows.league_id = leagues.id')
                      .joins('JOIN disciplines ON hows.discipline_id = disciplines.id')
                      .where("wheres.location_id = ? AND hows.discipline_id = ? ", params[:location_id],params[:discipline_id]).paginate(page: params[:page])

    end
  end
  def participate
    @league.participate(current_user)
    #@league.name= "Kurva!"
    @league.save
    redirect_to @league
  end
  def participants
    @league=League.find(params[:id])
    #@league.users= @league.users.paginate(page: params[:page]) # User.paginate(page: params[:page])
    @participants= @league.participates.paginate(page: params[:page])
    #@league.save
  end
  def index
    @leagues = League.all.paginate(page: params[:page])
  end
  def update
    @league = League.find(params[:id])
    @league.update_attributes(league_params)
      redirect_to :back
  end
  def events
   @league = League.find(params[:id])
   @events= @league.events.paginate(page: params[:page])
  end
  def closeevent
    @league = League.find(params[:id])
    @event= @league.events.find_by(id: params[:eid])
    @event.closed= true
    @event.save!
  end
  def leaderboards
    @league = League.find(params[:id])
    @points = PartInEvent.joins('JOIN events ON events.id = part_in_events.event_id')
    .joins('JOIN leagues ON events.league_id = leagues.id')
    .joins('JOIN participates ON participates.league_id = leagues.id')
    .joins('JOIN users ON users.id = participates.user_id')
    .where("participates.state = 1 AND leagues.id= ? AND part_in_events.user_id= users.id",@league.id)
    .select('users.name ,users.id , sum(score) as totalscore').group("users.id")

  end
    def delete
    @league = League.find(params[:id])
    @league.events.each do |p|
      p.part_in_events.each do |pie|
        pie.delete
      end
      p.delete
    end
    @league.participates.each do |p|
      p.delete
    end
    @league.hows.each do |h|
      h.delete
    end
    @league.wheres.each do |w|
      w.delete
    end
    @league.delete
    redirect_to leagues_path
  end
  private

  def league_params
    params.require(:league).permit(:information,:name,:id,:loc,:slocation,:sdiscipline, :begdate, :expenddate,:location_id, :discipline_id)
  end
end

app/helpers/league_helper.rb
module LeagueHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_league.html.erb

    <div  style=" padding: 5px 5px 5px 5px">
      <li><%= link_to league.name, league %></li>
     </div>

app/views/leagues/_sidebox.html.erb
<div class = "well" style="float: left; width: 20%">
<aside2 >
  <section>
    <ul class="nav pull-left">
      <li><%= link_to "Home", league_path %></li>
      <li><%= link_to "Participants", participants_league_path %></li>
      <li><%= link_to "Events", events_league_path %></li>
      <li><%= link_to "Leaderboards", leaderboards_league_path %></li>
      <li><%= link_to "Informations", edit_league_path %></li>
      <% if ( !current_user.nil? && @league.isAdmin?(current_user))%>
          <li><%= link_to "Manage", manage_league_path %></li>
      <%end%>
    </ul>
  </section>
</aside2>
</div>

app/views/leagues/closeevent.html.erb
<% provide(:title, 'Close event') %>
<h1>All participants</h1>
<div class= "row">
  <%= render "sidebox"%>
  <aside3 class="span5">
    <ul class="users">
      <%= form_for @event do |f| %>
        <% @event.part_in_events.each do |part_in_event| %>
          <li>
            <%= f.fields_for :part_in_events, part_in_event do |p| %>
                <%=  f.label part_in_event.user.name%>
                <%= p.text_field :score %>
                <%= p.hidden_field :part_in_event_id,:value=> part_in_event.id %>
            <%end%>
          </li>
       <%end%>
          <%= f.submit "Close Event", class: "btn btn-large btn-primary" %>
      <%end%>
    </ul>
  </aside3>
</div>

app/views/leagues/edit.html.erb
<% provide(:title, @league.name) %>
<h1>Informations</h1>

  <%= render "sidebox"%>
<div class="row">
  <ul class="nav pull-right"  >
    <div class="well">
    <li>
      <h5><b>Location:</b></h5>
      <%@league.locations.each do |location|%>
      <p style="padding-left: 10px "><%= location.name + ' ' %></p>
      <%end%>
    </li>
    <li>
      <h5><b>Discipline:</b></h5>
      <%@league.disciplines.each do |discip|%>
          <p style="padding-left: 10px "><%= discip.name + ' ' %></p>
      <%end%>
    </li>
    <li>
      <h5><b>Date of start:</b></h5>
      <p style="padding-left: 10px "><%= @league.begdate %></p>
    </li>
    <li>
      <h5><b>Expected date of end:</b></h5>
      <p style="padding-left: 10px "><%= @league.expenddate %></p>
    </li>
    <li>
      <h5><b>Founder:</b></h5>
      <p style="padding-left: 10px "><%= @league.admins.first.user.name%></p>
    </li>


    </div>
  </ul>
  <%if !@league.information.nil? %>
  <div class= "well" style=" float: left;width: 50%; margin: 0px 10px 10px 10px ">
    <%= @league.information %>
  </div>
  <%end%>
</div>

app/views/leagues/events.html.erb
<% provide(:title, 'League events') %>
<h1>League Events</h1>

  <%= render "sidebox"%>
<div class = "well" style="float: left; width: 50%; margin: 0px 10px 10px 10px">
  <aside3 class="span5">
    <ul class="users">

      <%= will_paginate @events %>
      <ul class="leagues">
        <% @events.each do |event| %>
            <%if event.closed== false%>
            <li>
              <div><%= event.name %></div>
              <div><%= event.date %></div>
              <div><%= event.address %></div>
              <div><%= event.info %></div>
            </li>
            <% if signed_in? && @league.isAdmin?(current_user)%>
                <%=link_to 'Close', closeevent_league_path(:eid=> event.id) %>
            <%end%>
            <%end%>
        <% end %>
      </ul>
      <%= will_paginate @events %>
    </ul>
  </aside3>
</div>

app/views/leagues/index.html.erb
<% provide(:title, 'All leagues') %>
<h1>All leagues</h1>
<%= will_paginate %>
<ul class="leagues">
  <%= render @leagues %>
</ul>
<%= will_paginate %>

app/views/leagues/leaderboards.html.erb
<% provide(:title, @league.name) %>
<h1>Leaderboards</h1>
<%= render "sidebox" %>
<div class = "well" style="float: right; width: 50%">
<table>
  <tr>
    <th> Name </th>
    <th style=" padding-left: 250px ; float: right"> Total Score</th>
  </tr>
  <% @points.each do |point| %>
      <tr>
        <td> <%= point.name %> </td>
        <td style=" padding-left: 250px ; float: right"><%= point.totalscore %></td>
      </tr>
  <%end%>
</table>
</div>

app/views/leagues/manage.erb
<% provide(:title, @league.name) %>
<h1><%= @league.name %></h1>
    <%= render "sidebox"%>

<div class= "well" style="float: right; width: 45%">
  <%= form_for @league do |f| %>
      <h4>Change Informations</h4>
      <div>
        <%= f.text_area :information,:value => @league.information, cols:20,rows:20 %>
      </div>
      <div style="float: left; width: 51%">
        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
      </div>
  <% end %>
 </div>

<div class= "well" style="float: left; width: 45%">
<%= form_for(@newspost) do |f| %>

    <%=f.hidden_field :league_id, :league_id => @newspost.league_id %>
    <div>
      <h4>Create Post</h4>
      <%= f.label 'Title'%>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label 'Content'%>
      <%= f.text_area :textcontent, cols:20,rows:20 %>
    </div>
    <div>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    </div>
<% end %>
 </div>

<div class= "well"  style="float: right; width: 45%">
  <%= form_for(@event) do |f| %>

      <%=f.hidden_field :league_id, :league_id => @newspost.league_id %>
      <div>
        <h4>Create Event</h4>
        <%= f.label 'Name'%>
        <%= f.text_field :name %>
      </div>
      <div>
        <%= f.label 'Adress'%>
        <%= f.text_field :address %>
      </div>
      <div>
        <%= f.label 'Date and Time'%>
        <%= f.datetime_select :date %>
      </div>
      <div >
        <%= f.label 'Informations'%>
        <%= f.text_area :info, cols:20,rows:5 %>
      </div>
      <div>
        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
      </div>
  <% end %>
</div>
<div class= "well"  style="float: left; width: 45%">
  <%=link_to 'Cancel League', delete_league_path,data: { confirm: "You sure?" } %>
</div>

app/views/leagues/new.html.erb
<% provide(:title, "New league") %>
<h1>Create your league</h1>


  <div class="span6 offset3">
    <div class="well" style="padding-bottom: 235px">
    <%= form_for(@league) do |f| %>


        <%= f.label :name %>
        <%= f.text_field :name %>

        <div style="float: left; width: 100%">
        <div style="float: left; width: 43%">
           <%=label_tag :location_id, 'Location' %>
           <%= f.collection_select :loc, Location.order("name"), :id, :name, {:selected => Location.find_by(name: " Other").id} %>
           <%= f.text_field :slocation %>
        </div>

        <div style="float: right; width: 43%">
          <%=label_tag :location_id, 'Discipline' %>
          <%= f.collection_select :discipline_id, Discipline.order("name"), :id, :name, {:selected => Discipline.find_by(name: " Other").id} %>
          <%= f.text_field :sdiscipline %>
        </div>
        </div>
        <div style="float: left; width: 46%">
          <%=  f.label 'Begin Date'%>
          <%= f.text_field :begdate, 'data-behaviour' => 'datepicker' %>
        </div>

        <div style="float: right; width: 46%">
          <%=  f.label 'Expected end date'%>
          <%= f.text_field :expenddate, 'data-behaviour' => 'datepicker' %>
        </div>

        <div style="float: right; width: 100%">
        <small>*Some attributes will be filled after your league is created</small>
        </div>
        <div style="float: left; width: 100%">
        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
        </div>
    <% end %>
    </div>

    <script type="text/javascript">
        var colsel1 = document.getElementById('league_loc');
        var textsel1 = document.getElementById('league_slocation');
        colsel1.onchange = function() {
            if(colsel1.value!=1){
                textsel1.style['display'] = 'none';
            }else {
                textsel1.style['display'] = 'block';
            }
        };
        var colsel2 = document.getElementById('league_discipline_id');
        var textsel2 = document.getElementById('league_sdiscipline');
        colsel2.onchange = function() {
            if(colsel2.value!=1){
                textsel2.style['display'] = 'none';
            }else {
                textsel2.style['display'] = 'block';
            }
        };
    </script>

</div>

app/views/leagues/participants.html.erb
<% provide(:title, 'All participants') %>
<h1>All participants</h1>
<%= render "sidebox"%>

<div class= "row">

  <aside3 class="span5">
    <div class="well">
    <ul class="users">

      <%= will_paginate @participants %>
      <ul class="leagues">
        <% @participants.each do |participant| %>
            <li>
              <%= gravatar_for participant.user %>
              <%= link_to participant.user.name, participant.user %>
              <% if signed_in? && @league.isAdmin?(current_user) %>
                  <div>

                  <% if participant.state==0 %>
                     signed
                  <% elsif participant.state==1%>
                     qualified
                  <% elsif participant.state==2%>
                     disqualified
                  <%end%>
                  </div>
                  <div>
                  <% if participant.state== 0 %>
                      |   <%=link_to 'Qualify', qualify_participate_path(:id=> participant.id) %>
                  <% elsif participant.state==1 %>
                      <%=link_to 'Disqualify', disqualify_participate_path(:id=> participant.id) %>
                  <%end%>
                  </div>
              <% end %>
            </li>
        <% end %>
      </ul>
      <%= will_paginate @participants %>
    </ul>
    </div>
  </aside3>
</div>


app/views/leagues/search.html.erb
<% provide(:title, "Search leagues") %>

<div class="row">

  <%= form_tag '/searchleague', method: :get do %>

      <div class="well">
        <div style="clear:both"></div>


        <div style="width: 100%;">

          <div style="float: left; width: 43%">
          <%= label_tag :location_id, 'Location' %>
          <%= collection_select(:location_id, nil , Location.order('name'), :id, :name, {:selected => @location}) %>
        </div>

          <div style="float: left; width: 43%">
            <%= label_tag :location_id, 'Discipline' %>
            <%= collection_select(:discipline_id, nil , Discipline.order('name'), :id, :name, {:selected => @location}) %>
          </div>

          <div style="float: right;">
            <%= submit_tag '  Search  ', class: "btn btn-large btn-primary" %>
          </div>

        </div>

        <div style="clear:both"></div>

      </div>

  <% end %>

  <h3>Found Leagues: </h3>

  <hr>

 <% if  !signed_in? && ( @leagues.nil? || @leagues.count == 0)  %>
      <div class="well">
        <big>Sorry, we have no leagues that fulfill your requirements.</big>
      </div>
  <% elsif  @leagues.nil? || @leagues.count == 0 %>
      <div class="well">
        <big>Sorry, we have no leagues that fulfill your requirements. You can <%= link_to "create", new_league_path %> your own league</big>
      </div>
  <%else%>
      <%= will_paginate(@leagues) %>
      <%= render @leagues %>
      <%= will_paginate(@leagues) %>


  <% end %>


</div>

app/views/leagues/show.html.erb
<% provide(:title, @league.name) %>
<h1><%= @league.name %></h1>
  <%= render "sidebox"%>

<div class = "well" style="float: right; width: 70% ;padding:  10px 10px 10px 10px " >
  <ul class="users">
    <%= render @league.newsposts.reverse %>
  </ul>
</div>
<div style="clear: left;">
<% if signed_in? &&  !@league.isParticipating?(current_user)%>
    <%= form_for @participate do |f| %>
        <div style="float: left; width: 80%">
          <%= f.hidden_field(:league_id,  :value => @league.id) %>
          <%= f.submit "Join", class: "btn btn-large btn-primary" %>
        </div>
    <% end %>
<%end%>
</div>