config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :users do
    member do
      get 'participations'
      get 'events'
    end
  end
  resources :newsposts
  resources :sessions, only: [:new,:create,:destroy]
  resources :part_in_events do
    member do
      get 'pick'
      get 'unpick'
    end
  end
  resources :events
  resources :participates do
    member do
      get 'qualify'
      get 'disqualify'
    end
  end
  resources :leagues do
    member do
      get 'participants'
      get 'manage'
      get 'events'
      get 'closeevent'
      get 'leaderboards'
	  get 'delete'
    end
  end
  get 'static_pages/home'
  get 'static_pages/contact'
  post  '/leagues/:id', to: 'leagues#show'
  match '/searchleague', to: 'leagues#search', via: 'get'
  match '/newleague' ,  to: 'leagues#new' ,         via: 'get'
  match '/signin' ,  to: 'sessions#new' ,         via: 'get'
  match '/signout' , to: 'sessions#destroy' ,     via: 'delete'
  match '/home' , to: 'static_pages#home' , via: 'get'
  match '/help' , to: 'static_pages#help' , via: 'get'
  match '/signup' , to: 'users#new' , via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, length: {minimum: 6}
  has_secure_password

  has_many :participates, foreign_key:  "user_id",dependent:  :destroy
  has_many :leagues, through: :participates, source: :league

  has_many :part_in_events, foreign_key:  "user_id",dependent:  :destroy
  has_many :events, through: :part_in_events, source: :event

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index,:edit, :update]
  before_action :correct_user, only: [:edit,:update]
  before_action :admin_user, only: :destroy
  def show
    @user = User.find(params[:id])
    @news= Newspost.joins('JOIN leagues ON leagues.id = newsposts.league_id')
    .joins('JOIN participates ON participates.league_id = leagues.id')
    .joins('JOIN users ON users.id  = participates.user_id ')
    .where("users.id = ? ", params[:id]).order(created_at: :desc).paginate(page: params[:page])
  end
  def events
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def index
    @users= User.paginate(page: params[:page])
  end
  def create
    @user= User.new(user_params)
    if(@user.save)
      sign_in @user
      flash[:success] = "Welcome to the LeagueA!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end
  def participations
    @user = User.find(params[:id])
    @leagues= @user.leagues
    @leagues= @leagues.paginate(page: params[:page])
  end
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end
  end
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_sidebox.html.erb

<div style="float: left; width: 30%">
  <aside2 >
    <section>
      <ul class="nav pull-left">
        <li><%= link_to "Home", user_path %></li>
        <li><%= link_to "Upcoming events", events_user_path %></li>
        <li><%= link_to "My participations", participations_user_path %></li>
      </ul>
    </section>
  </aside2>
</div>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                    data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/events.html.erb
<% provide(:title, "My Events") %>
<div class= "well" style= "padding-top: 20px; width: 20%;float: left" >
  <aside class="span5">
    <section>
      <h1>
        <%= @user.name %>


      </h1>
      <%= gravatar_for @user %>
    </section>
    <%= render "sidebox" %>
  </aside>
</div>
<h1>Upcoming events</h1>
<div class= "well" style="float: left; width: 65%;margin: 10px 10px 10px 10px" >
    <section>
      <ul>
        <%= render @user.events %>
      </ul>
    </section>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/participations.html.erb
<% provide(:title, 'My participations') %>

<div class= "well" style= "padding-top: 20px; width: 20%;float: left" >
  <aside class="span5">
    <section>
      <h1>
        <%= @user.name %>


      </h1>
      <%= gravatar_for @user %>
    </section>
    <%= render "sidebox" %>
  </aside>
</div>
<h1>Your participations</h1>
<div class= "well" style="float: left; width: 65%;margin: 10px 10px 10px 10px" >
<ul>
  <%= render @leagues %>
</ul>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class = "well" style= "padding-top: 20px; width: 20%;float: left" >
  <aside class="span5">
    <section>
      <h1>
        <%= @user.name %>


      </h1>
      <%= gravatar_for @user %>
    </section>
    <%= render "sidebox" %>
  </aside>
</div>
<div class = "well" style="float: right; width: 70%"  >
  <div style=" float: left ; padding-left: 50%;width: 50%  " >
  <h3>News</h3>
  </div>
  <div style=" float: left ;padding: 5px 5px 5px 5px;margin: 5px 5px 5px 5px; width: 100%  " >
    <% if !@news.nil?%>
    <%  @news.each do |newspost| %>
        <h5><%= newspost.title%>  (<%=newspost.league.name %>)</h5>
        <div style="padding: 7px 5px 5px 10px">
          <div> <%= word_wrap newspost.textcontent, line_width: 10 %></div>
        </div>
    <%end%>
    <%end%>
  </div>


</div>
