config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :users do
    member do
      get 'participations'
      get 'events'
    end
  end
  resources :newsposts
  resources :sessions, only: [:new,:create,:destroy]
  resources :part_in_events do
    member do
      get 'pick'
      get 'unpick'
    end
  end
  resources :events
  resources :participates do
    member do
      get 'qualify'
      get 'disqualify'
    end
  end
  resources :leagues do
    member do
      get 'participants'
      get 'manage'
      get 'events'
      get 'closeevent'
      get 'leaderboards'
	  get 'delete'
    end
  end
  get 'static_pages/home'
  get 'static_pages/contact'
  post  '/leagues/:id', to: 'leagues#show'
  match '/searchleague', to: 'leagues#search', via: 'get'
  match '/newleague' ,  to: 'leagues#new' ,         via: 'get'
  match '/signin' ,  to: 'sessions#new' ,         via: 'get'
  match '/signout' , to: 'sessions#destroy' ,     via: 'delete'
  match '/home' , to: 'static_pages#home' , via: 'get'
  match '/help' , to: 'static_pages#help' , via: 'get'
  match '/signup' , to: 'users#new' , via: 'get'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :league, class_name: "League"

  has_many :part_in_events, foreign_key: "event_id"
  has_many :users, through: :part_in_events, source: :user

  accepts_nested_attributes_for :part_in_events

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event= Event.new()
  end
  def create
    @event= Event.create!(post_params)
    redirect_to @event #action:  'setpeople'
    #redirect_to action: 'manage'
  end

  def pick

    redirect_to :back
  end
  def unpick

  end
  def show
    @event= Event.find_by(id: params[:id])
    @participants = @event.league.participates.paginate(page: params[:page])
  end
  def update
    @event = Event.find(params[:id])
    @event.update(post_params)
    @event.save!
    redirect_to @event.league
  end
  private
  def post_params
    params.require(:event).permit(:league_id,:name,:info,:date,:address,
                                  :part_in_events_attributes => [:id,:score])
  end
  def part_params
    params.require(:part_in_event).permit(:score)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<%if event.closed== false%>
<li>
  <div>
  <%= event.name %>
  </div>
  <div>
  <%= event.address %>
  </div>
  <div>
  <%= event.date %>
  </div>
  <div>
  <%= event.info %>
  </div>
</li>
<%end%>

app/views/events/show.html.erb
<% provide(:title, 'Pick participants') %>
<h1>Pick participants</h1>
<div class= "row">
  <aside3 class="span5">
    <ul class="users">

      <%= will_paginate @participants %>
      <ul class="leagues">
        <% @participants.each do |participant| %>
            <%if participant.state == 1%>
            <li>
              <%= gravatar_for participant.user %>
              <%= link_to participant.user.name, participant.user %>
              <% if !@event.users.find_by(id: participant.user.id)%>
                  <%=link_to 'Pick', pick_part_in_event_path(:pid=> participant.id) %>
              <% else %>
                  <%=link_to 'Unpick', unpick_part_in_event_path(:pid=> participant.id) %>
              <% end%>
            </li>
            <%end%>
        <% end %>
      </ul>
      <%= will_paginate @participants %>
    </ul>
    <div>
    <%=link_to 'Done', manage_league_path(:id => @event.league_id) %>
        </div>
  </aside3>
</div>