config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :users do
    member do
      get 'participations'
      get 'events'
    end
  end
  resources :newsposts
  resources :sessions, only: [:new,:create,:destroy]
  resources :part_in_events do
    member do
      get 'pick'
      get 'unpick'
    end
  end
  resources :events
  resources :participates do
    member do
      get 'qualify'
      get 'disqualify'
    end
  end
  resources :leagues do
    member do
      get 'participants'
      get 'manage'
      get 'events'
      get 'closeevent'
      get 'leaderboards'
	  get 'delete'
    end
  end
  get 'static_pages/home'
  get 'static_pages/contact'
  post  '/leagues/:id', to: 'leagues#show'
  match '/searchleague', to: 'leagues#search', via: 'get'
  match '/newleague' ,  to: 'leagues#new' ,         via: 'get'
  match '/signin' ,  to: 'sessions#new' ,         via: 'get'
  match '/signout' , to: 'sessions#destroy' ,     via: 'delete'
  match '/home' , to: 'static_pages#home' , via: 'get'
  match '/help' , to: 'static_pages#help' , via: 'get'
  match '/signup' , to: 'users#new' , via: 'get'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
    belongs_to :user, class_name: "User"
    belongs_to :league, class_name: "League"
    validates :user_id, presence: true
    validates :league_id, presence: true
end

app/models/discipline.rb
#encoding: utf-8
class Discipline< ActiveRecord::Base
  has_many :hows, foreign_key: "discipline_id", dependent: :destroy
  has_many :leagues, through: :hows, source: :league

  has_many :reverse_hows, foreign_key:  "discipline_id",
           class_name: "how",
           dependent:  :destroy
  has_many :leagues, through:  :reverse_hows, source: :league
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :league, class_name: "League"

  has_many :part_in_events, foreign_key: "event_id"
  has_many :users, through: :part_in_events, source: :user

  accepts_nested_attributes_for :part_in_events

end

app/models/how.rb
class How < ActiveRecord::Base
  belongs_to :discipline, class_name: "Discipline"
  belongs_to :league, class_name: "League"
  validates :discipline_id, presence: true
  validates :league_id, presence: true
end

app/models/league.rb
class League < ActiveRecord::Base
  has_many :participates, foreign_key:  "league_id",dependent:  :destroy
  has_many :users, through: :participates, source: :user

  has_many :wheres, foreign_key: "league_id", dependent: :destroy
  has_many :locations, through: :wheres, source: :location

  has_many :hows, foreign_key: "league_id", dependent: :destroy
  has_many :disciplines, through: :hows, source: :discipline

  has_many :admins, foreign_key: "league_id", dependent: :destroy

  has_many :newsposts, foreign_key: "league_id", dependent: :destroy

  has_many :events, foreign_key: "league_id", dependent: :destroy

  def setDisc!(some_discipline)
    hows.create!(discipline_id: some_discipline.id)
  end
  def isAdmin?(some_user)
    admins.find_by(user_id: some_user.id)
  end
  def setAdmin!(some_user)
    admins.create!(user_id: some_user.id)
  end
  def kickAdmin!(some_user)
    admins.find_by(user_id: some_user.id).destroy
  end
  def participate(some_user)
    participates.create!(user_id: some_user.id)
  end
  def isParticipating?(some_user)
    participates.find_by(user_id: some_user.id)
  end
  def unparticipate!(some_user)
    participates.find_by(user_id: some_user.id).destroy
  end
  def hasDisc?(some_discipline)
    hows.find_by(discipline_id: some_discipline.id)
  end

  def unSetDisc!(some_discipline)
    hows.find_by(discipline_id: some_discipline.id).destroy
  end

  def place!(some_location)
    wheres.create!(location_id: some_location.id)
  end
  def placed?(some_location)
    wheres.find_by(location_id: some_location.id)
  end
  def displace!(some_location)
    wheres.find_by(location_id: some_location.id).destroy
  end
end

app/models/location.rb
#encoding: utf-8
class Location < ActiveRecord::Base
  has_many :wheres, foreign_key: "location_id", dependent: :destroy
  has_many :leagues, through: :wheres, source: :league

  has_many :reverse_wheres, foreign_key:  "location_id",
                            class_name: "where",
                            dependent:  :destroy
  has_many :leagues, through:  :reverse_wheres, source: :league
end

app/models/newspost.rb
class Newspost < ActiveRecord::Base
  belongs_to :league, class_name: "League"
end

app/models/part_in_event.rb
class PartInEvent < ActiveRecord::Base
  belongs_to :event, class_name: "Event"
  belongs_to :user, class_name: "User"
end

app/models/participate.rb
class Participate < ActiveRecord::Base
  validates :user_id, uniqueness: { :scope => [:league_id],
      message: "You are already participating"}
  belongs_to :league, class_name: "League"
  belongs_to :user, class_name: "User"


end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, length: {minimum: 6}
  has_secure_password

  has_many :participates, foreign_key:  "user_id",dependent:  :destroy
  has_many :leagues, through: :participates, source: :league

  has_many :part_in_events, foreign_key:  "user_id",dependent:  :destroy
  has_many :events, through: :part_in_events, source: :event

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private
  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end
end

app/models/where.rb
class Where < ActiveRecord::Base
  belongs_to :location, class_name: "Location"
  belongs_to :league, class_name: "League"
  validates :location_id, presence: true
  validates :league_id, presence: true
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/league_helper.rb
module LeagueHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/newsposts_helper.rb
module NewspostsHelper
end

app/helpers/participates_helper.rb
module ParticipatesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end
  def signed_in?
    !current_user.nil?
  end
  def current_user= (user)
    @current_user = user
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  def sign_out
    current_user.update_attribute(:remember_token, User.hash(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil;
  end
  def current_user?(user)
    user== current_user
  end
  def redirect_back_or(default)
    redirect_to(session[:return_to]||default)
    session.delete(:return_to)
  end
  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<div style="float: left; width: 49% ;padding:  10px 10px 10px 10px " >
        <p>LeagueA v0.11 © Michal Farkaš</p>
</div>
<div style="float: right; width: 10% ;padding:  10px 10px 10px 10px " >
  <%= link_to "About", help_path %>
  <%= link_to "Contact", static_pages_contact_path %>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">

    <div class="container">
      <nav>
        <%= link_to image_tag("logo.png", :border => 0), {:action => 'home', :controller => 'static_pages'}, {:class => 'dock-item'} %>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", help_path %></li>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Leagues <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Search", searchleague_path %></li>
              <li><%= link_to "All Leagues",  leagues_path %></li>
              <% if signed_in? %>
              <li><%= link_to "Create League", newleague_path %></li>
              <%end%>
            </ul>
          </li>

          <% if signed_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</div>
<div>
  <%= debug(params) if Rails.env.development? %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@user.errors.count, "error") %>.
      </div>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>